language: r
cache: packages
warnings_are_errors: true

r_packages:
  - covr

r_github_packages:
  - jimhester/covr

before_install:
  - sudo apt-get update

apt_packages:
  - r-cran-rcpp
#   - r-cran-rcpparmadillo

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
